package com.enterprise.usco.uvscannerservidor.data;
// Generated 18/08/2017 11:37:09 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonFormat;
import com.vividsolutions.jts.geom.Point;
import java.util.Calendar;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.Type;

/**
 * Track generated by hbm2java
 */
@Entity
@Table(name="datauvi")
public class DataUV  implements java.io.Serializable {


     private Integer id;
     private Date fechaServidor;
     private Float lectura;
     private Float uvi;
     private Float latitud;
     private Float longitud;
     
    public DataUV() {
    }

   
    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
 
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd/HH/mm/ss", timezone = JsonFormat.DEFAULT_TIMEZONE)
    @Column(name="fecha_servidor", nullable=false, length=19)
    public Date getFechaServidor() {
        return this.fechaServidor;
    }
    /*@Column(name="fecha_servidor", nullable=false, length=19)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd/HH/mm/ss/SSSZ",timezone = JsonFormat.DEFAULT_TIMEZONE)//,timezone = "GMT-5",locale = "GMT-5")
    public Date getFechaServidor() {
        return fechaServidor!=null?mapearTimeZone(fechaServidor):null;
    }*/
    public Date mapearTimeZone(Date fecha) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fecha);
        Long tiempo = fecha.getTime() + Calendar.getInstance().get(Calendar.ZONE_OFFSET);
        Date fechaSalida = new Date(tiempo);
        return fechaSalida;
    }
    
    
    public void setFechaServidor(Date fechaServidor) {
        this.fechaServidor = fechaServidor;
    }

    @Column(name="lectura")
    public Float getLectura() {
        return this.lectura;
    }
    
    public void setLectura(Float lectura) {
       this.lectura = lectura;
    }
    
    @Column(name="uvi")
    public Float getUvi() {
        return uvi;
    }

    public void setUvi(Float uvi) {
        this.uvi = uvi;
    }
     
    @Column(name="latitud")
    public Float getLatitud() {
        return latitud;
    }

    public void setLatitud(Float latitud) {
        this.latitud = latitud;
    }
    
    @Column(name="longitud")
    public Float getLongitud() {
        return longitud;
    }

    public void setLongitud(Float longitud) {
        this.longitud = longitud;
    }
    
    
    
}


